// <auto-generated />
namespace NutShopping.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editorder_remark_max : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editorder_remark_max));
        
        string IMigrationMetadata.Id
        {
            get { return "202111121725011_edit-order_remark_max"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
