// <auto-generated />
namespace NutShopping.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editsubscription_cycle_delete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editsubscription_cycle_delete));
        
        string IMigrationMetadata.Id
        {
            get { return "202111060822476_edit-subscription_cycle_delete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
