// <auto-generated />
namespace NutShopping.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editproduct_deleteImg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editproduct_deleteImg));
        
        string IMigrationMetadata.Id
        {
            get { return "202111090644359_edit-product_deleteImg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
