// <auto-generated />
namespace NutShopping.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editrecipt_summary_length : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editrecipt_summary_length));
        
        string IMigrationMetadata.Id
        {
            get { return "202111190946178_edit-recipt_summary_length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
