// <auto-generated />
namespace NutShopping.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editproducts_NutritionFacts_notrequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editproducts_NutritionFacts_notrequired));
        
        string IMigrationMetadata.Id
        {
            get { return "202111161336391_edit-products_NutritionFacts_notrequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
